# file: C:\Users\erena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\joblib\externals\loky\process_executor.py
# hypothesis_version: 6.140.2

[0.001, 1.0, 1.2, 5.0, 300000000.0, 256, 'Exited cleanly', 'Exiting with code 1', 'LOKY_MAX_DEPTH', 'PYTHONFAULTHANDLER', 'SC_SEM_NSEMS_MAX', '__traceback__', 'args', 'broken executor', 'chunksize', 'closing call_queue', 'closing result_queue', 'fn', 'fork', 'future', 'kwargs', 'timeout', 'win32']