# file: C:\Users\erena\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIL\ImageFile.py
# hypothesis_version: 6.140.2

[1024, 65536, 'Error closing: %s', 'P', 'Truncated File Read', '_exif_offset', '_fp', '_n_frames', 'bad configuration', 'cannot reuse parsers', 'decoding error', 'encoderconfig', 'flush', 'image was incomplete', 'load_read', 'load_seek', 'n_frames', 'out of memory error', 'raise_oserror', 'raw', 'rb', 'tile_prefix', 'unknown error']